export { default as Welcome } from "./welcome/Welcome";
export { default as HomeLayout } from "./homeLayout/HomeLayout";
export { default as Login } from "./login/Login";
export { default as SignUp } from "./signUp/SignUp";
export { default as Products } from "./products/Products";
export { default as Profile } from "./profile/Profile";
export { default as Favorites } from "./favorites/Favorites";
export { default as Collections } from "./collections/Collections";
export { default as Error } from "./error/Error";
